sudo: required
services:
  - docker

before_install:
  - docker build -t vsuzdaltsev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vsuzdaltsev/docker-react npm run test -- --coverage

