sudo: required
services:
  - docker

before_install:
  - docker build -t vsuzdaltsev/docker-react -f Dockerfile.dev .

script:
  - docker run vsuzdaltsev/docker-react npm test
#run test -- --coverage
